#!/bin/sh

if [ $# -eq 4 ]
  then
    echo "Usage $DOMAIN $SSL_DOMAINS $SMTP_USER $SMTP_PASSWORD"
    exit 1
fi

DOMAIN="$1"
SSL_DOMAINS="$2"
SMTP_USER="$3"
SMTP_PASSWORD="$4"

echo $DOMAIN $SSL_DOMAINS $SMTP_USER $SMTP_PASSWORD